name: daily_extensions
description: Set of most useful Dart extensions for daily use that increases development velocity.
version: 1.0.6
homepage: https://github.com/phimary/daily_extensions

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0