name: daily_extensions
description: Most useful extensions for daily use.
version: 1.0.0
homepage: https://github.com/phimary/daily_extensions

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0